# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import djorm_pgarray.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20141011_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Alpha_Carot_mig',
            new_name='alpha_carot_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Beta_Carot_mig',
            new_name='beta_carot_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Beta_Crypt_mig',
            new_name='beta_crypt_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Calcium_mg',
            new_name='calcium_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Carbohydrt_g',
            new_name='carbohydrt_g',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Cholestrl_mg',
            new_name='cholestrl_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Choline_Tot_mg',
            new_name='choline_tot_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Copper_mg',
            new_name='copper_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='energy_Kcal',
            new_name='energy_kcal',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='FA_Mono_g',
            new_name='fa_mono_g',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='FA_Poly_g',
            new_name='fa_poly_g',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='FA_Sat_g',
            new_name='fa_sat_g',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Fiber_TD_g',
            new_name='fiber_td_g',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Folate_DFE_mig',
            new_name='folate_dfe_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Folate_Tot_mig',
            new_name='folate_tot_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Folic_Acid_mig',
            new_name='folic_acid_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Food_Folate_mig',
            new_name='food_folate_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='GmWt_1',
            new_name='gmwt_1',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='GmWt_2',
            new_name='gmwt_2',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='GmWt_Desc1',
            new_name='gmwt_desc1',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='GmWt_Desc2',
            new_name='gmwt_desc2',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Iron_mg',
            new_name='iron_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Lut_Zea_mig',
            new_name='lut_zea_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Lycopene_mig',
            new_name='lycopene_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Magnesium_mg',
            new_name='magnesium_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Manganese_mg',
            new_name='manganese_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Niacin_mg',
            new_name='niacin_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Panto_Acid_mg',
            new_name='panto_acid_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Phosphorus_mg',
            new_name='phosphorus_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Potassium_mg',
            new_name='potassium_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Refuse_Pct',
            new_name='refuse_pct',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Retinol_mig',
            new_name='retinol_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Riboflavin_mg',
            new_name='riboflavin_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Selenium_mig',
            new_name='selenium_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Sodium_mg',
            new_name='sodium_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Sugar_Tot_g',
            new_name='sugar_tot_g',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Thiamin_mg',
            new_name='thiamin_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_A_IU',
            new_name='vit_a_iu',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_A_RAE',
            new_name='vit_a_rae',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_B12_mig',
            new_name='vit_b12_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_B6_mg',
            new_name='vit_b6_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_C_mg',
            new_name='vit_c_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_D_IU',
            new_name='vit_d_iu',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_D_mig',
            new_name='vit_d_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_E_mg',
            new_name='vit_e_mg',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Vit_K_mig',
            new_name='vit_k_mig',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='Zinc_mg',
            new_name='zinc_mg',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=djorm_pgarray.fields.ArrayField(default=None, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time_seconds',
            field=models.IntegerField(default=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
